version: "3.9"  # optional since v1.27.0
services:
  db:
    image: postgres
    container_name: postgres-db-tg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=post123
      - POSTGRES_DB=bot-db
    ports:
      - "6432:5432"
#    volumes:
#      - ./pg_data:/var/lib/postgresql/data/pgdata - нужно как-то научиться сохранять БД
  bot:
    build: ./bot
    container_name: tg-bot
    env_file: ./bot/.env
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - SERVER_HOST=server
      - SERVER_PORT=9090
    ports:
      - "49160:8080"
    links:
      - server
  server:
    build: ./server
    container_name: server
    env_file: ./server/.env
    environment:
      - POSTGRES_USERNAME=$POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_NAME=$POSTGRES_NAME
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DIALECT=$POSTGRES_DIALECT
      - SERVER_HOST=server
      - SERVER_PORT=9090
    ports:
      - "59160:9090"
    links:
      - db
